# Generated by Django 3.1.7 on 2021-03-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
