# Generated by Django 3.1.7 on 2021-03-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_service', '0002_auto_20210317_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songdetail',
            old_name='genre',
            new_name='name',
        ),
    ]
