# Generated by Django 3.2 on 2021-04-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_service', '0003_auto_20210317_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='song',
        ),
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
