# Generated by Django 3.2 on 2021-04-16 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_service', '0005_auto_20210416_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='username',
            new_name='user_id',
        ),
    ]
