# Generated by Django 3.2 on 2021-04-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_service', '0006_rename_username_rating_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
