# Generated by Django 3.2 on 2021-04-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_service', '0009_artist_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='song',
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
