# Generated by Django 3.2 on 2021-04-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_service', '0011_alter_rating_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
    ]
